from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 351)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MK/PycharmProjects/Phase_analysis/img/images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.checkBoxTGA = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxTGA.setFont(font)
        self.checkBoxTGA.setObjectName("checkBoxTGA")
        self.verticalLayout_2.addWidget(self.checkBoxTGA)
        self.checkBoxCOM = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxCOM.setFont(font)
        self.checkBoxCOM.setObjectName("checkBoxCOM")
        self.verticalLayout_2.addWidget(self.checkBoxCOM)
        self.checkBoxGPA_TGA_org = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_TGA_org.setFont(font)
        self.checkBoxGPA_TGA_org.setObjectName("checkBoxGPA_TGA_org")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_TGA_org)
        self.checkBoxGPA_TGA_a3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_TGA_a3.setFont(font)
        self.checkBoxGPA_TGA_a3.setObjectName("checkBoxGPA_TGA_a3")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_TGA_a3)
        self.checkBoxGPA_TGA_hyd = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_TGA_hyd.setFont(font)
        self.checkBoxGPA_TGA_hyd.setObjectName("checkBoxGPA_TGA_hyd")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_TGA_hyd)
        self.checkBoxGPA_COM_org = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_COM_org.setFont(font)
        self.checkBoxGPA_COM_org.setObjectName("checkBoxGPA_COM_org")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_COM_org)
        self.checkBoxGPA_COM_a3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_COM_a3.setFont(font)
        self.checkBoxGPA_COM_a3.setObjectName("checkBoxGPA_COM_a3")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_COM_a3)
        self.checkBoxGPA_COM_hyd = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGPA_COM_hyd.setFont(font)
        self.checkBoxGPA_COM_hyd.setObjectName("checkBoxGPA_COM_hyd")
        self.verticalLayout_2.addWidget(self.checkBoxGPA_COM_hyd)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_save_excel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save_excel.setFont(font)
        self.pushButton_save_excel.setObjectName("pushButton_save_excel")
        self.horizontalLayout.addWidget(self.pushButton_save_excel)
        self.pushButton_save_ascii = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save_ascii.setFont(font)
        self.pushButton_save_ascii.setObjectName("pushButton_save_ascii")
        self.horizontalLayout.addWidget(self.pushButton_save_ascii)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_done = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_done.sizePolicy().hasHeightForWidth())
        self.pushButton_done.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setObjectName("pushButton_done")
        self.verticalLayout.addWidget(self.pushButton_done)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Save"))
        self.label_10.setText(_translate("MainWindow", "Phase Analyses to Save"))
        self.checkBoxTGA.setText(_translate("MainWindow", "TGA (Weight Loss)"))
        self.checkBoxCOM.setText(_translate("MainWindow", "Computrac (Weight Loss)"))
        self.checkBoxGPA_TGA_org.setText(_translate("MainWindow", "GPA with TGA-Original Sample Weight Loss"))
        self.checkBoxGPA_TGA_a3.setText(_translate("MainWindow", "GPA with TGA-Humidified and Dried Sample Weight Loss"))
        self.checkBoxGPA_TGA_hyd.setText(_translate("MainWindow", "GPA with TGA-Hydrated and Dried Sample Weight Loss"))
        self.checkBoxGPA_COM_org.setText(_translate("MainWindow", "GPA with COMPUTRAC-Original Sample Weight Loss"))
        self.checkBoxGPA_COM_a3.setText(_translate("MainWindow", "GPA with COMPUTRAC-Humidified and Dried Sample Weight Loss"))
        self.checkBoxGPA_COM_hyd.setText(_translate("MainWindow", "GPA with COMPUTRAC-Hydrated and Dried Sample Weight Loss"))
        self.pushButton_save_excel.setText(_translate("MainWindow", "Save to Excel"))
        self.pushButton_save_ascii.setText(_translate("MainWindow", "Save to ASCII"))
        self.pushButton_done.setText(_translate("MainWindow", "Done!"))